AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*' # for cicleci

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
