---
version: 2
jobs:
  build:
    working_directory: ~/monte-event-tickets
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: monte-event-tickets
          RAILS_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: smonte-event-tickets_test
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: monte-event-tickets-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: sudo apt install -y postgresql-client || true

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: monte-event-tickets-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:structure:load

      # Run the tests
      - run: bundle exec rspec spec

      # Run the linters
      - run: bundle exec reek
      - run: bundle exec rubocop
